import streamlit as st 
import google.generativeai as genai

GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]

genai.configure(api_key=GEMINI_API_KEY)

generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 64,
  "max_output_tokens": 8192,
  "response_mime_type": "application/json",
}

model = genai.GenerativeModel(
  model_name="gemini-1.5-flash",
  generation_config=generation_config,
  # safety_settings = Adjust safety settings
  # See https://ai.google.dev/gemini-api/docs/safety-settings
)

def get_ai_recommended_poses(user_input):

  response = model.generate_content([
    "You are a helpful assistant bot that is designed to answer questions related to Yoga. Don't deviate from it. Stick to it and if something is out of the topic, return the output saying like please ask questions related to Yoga.",
    "input: {\n  \"experience_level\": \"Beginner\",\n  \"goals\": [\n    \"Flexibility\",\n    \"Relaxation\"\n  ],\n  \"limitations\": \"\"\n}",
    "output: {\n  \"yoga_poses\": [\n    {\n      \"name\": \"Child's Pose\",\n      \"sanskrit_name\": \"Balasana\",\n      \"benefits\": \"Stretches hips, thighs, and ankles; promotes relaxation.\",\n      \"best_time_to_do\": \"Anytime during your practice, especially at the beginning or as a resting pose between more challenging asanas.\",\n      \"suggestions_tips\": \"Focus on deep breathing while maintaining a gentle stretch. Use a bolster or folded blanket under your forehead if needed.\"\n    },\n    {\n      \"name\": \"Cat-Cow Pose\",\n      \"sanskrit_name\": \"Marjaryasana-Bitilasana\",\n      \"benefits\": \"Improves flexibility in the spine; promotes relaxation through synchronized breathing.\",\n      \"best_time_to_do\": \"As part of a warm-up sequence at the beginning of your practice.\",\n      \"suggestions_tips\": \"Move with your breath, arching and rounding your spine fluidly. Focus on the movement originating from your core.\"\n    },\n    {\n      \"name\": \"Downward-Facing Dog\",\n      \"sanskrit_name\": \"Adho Mukha Svanasana\",\n      \"benefits\": \"Stretches hamstrings, calves, and shoulders; calms the mind and relieves stress.\",\n      \"best_time_to_do\": \"As part of a sequence to energize and stretch the entire body, such as during sun salutations.\",\n      \"suggestions_tips\": \"Press evenly through your hands and feet, lengthening your spine. Keep your neck relaxed and gaze towards your navel.\"\n    },\n    {\n      \"name\": \"Seated Forward Bend\",\n      \"sanskrit_name\": \"Paschimottanasana\",\n      \"benefits\": \"Stretches the spine, hamstrings, and shoulders; promotes flexibility and relaxation.\",\n      \"best_time_to_do\": \"Towards the end of your practice to release tension in the spine and hamstrings.\",\n      \"suggestions_tips\": \"Reach forward with a flat back before gently folding. Use a strap around your feet if you cannot reach your toes comfortably.\"\n    },\n    {\n      \"name\": \"Corpse Pose\",\n      \"sanskrit_name\": \"Savasana\",\n      \"benefits\": \"Allows for complete rest and integration of yoga practice; relaxes the body and calms the mind.\",\n      \"best_time_to_do\": \"At the end of your practice as a final relaxation pose.\",\n      \"suggestions_tips\": \"Lie down comfortably, close your eyes, and allow your body to sink into the floor. Focus on releasing tension from head to toe.\"\n    }\n  ]\n}",
    "input: {\n\"experience_level\": \"Intermediate\",\n\"goals\": [\n\"Flexibility\",\n\"Relaxation\",\n\"Strength\"\n],\n\"limitations\": \"\"\n}",
    "output: {\n  \"yoga_poses\": [\n    {\n      \"name\": \"Triangle Pose\",\n      \"sanskrit_name\": \"Trikonasana\",\n      \"benefits\": \"Strengthens legs, stretches hips and hamstrings, improves balance and flexibility.\",\n      \"best_time_to_do\": \"During a standing pose sequence, focusing on alignment and extension.\",\n      \"suggestions_tips\": \"Engage your core and press through your feet. Keep your chest and hips open to the side.\"\n    },\n    {\n      \"name\": \"Bridge Pose\",\n      \"sanskrit_name\": \"Setu Bandhasana\",\n      \"benefits\": \"Strengthens back, glutes, and legs; opens chest and shoulders, improves spine flexibility.\",\n      \"best_time_to_do\": \"Mid-practice as a backbend or after seated poses to counterbalance.\",\n      \"suggestions_tips\": \"Press feet and arms firmly into the mat. Lift hips while keeping knees in line with ankles.\"\n    },\n    {\n      \"name\": \"Warrior II Pose\",\n      \"sanskrit_name\": \"Virabhadrasana II\",\n      \"benefits\": \"Builds stamina and concentration, strengthens legs and core muscles, opens hips and chest.\",\n      \"best_time_to_do\": \"As part of a standing pose sequence, focusing on grounding and stability.\",\n      \"suggestions_tips\": \"Front knee aligned over ankle, back leg straight and strong. Extend arms actively and gaze over front fingertips.\"\n    },\n    {\n      \"name\": \"Seated Twist\",\n      \"sanskrit_name\": \"Ardha Matsyendrasana\",\n      \"benefits\": \"Increases spine mobility, massages abdominal organs, improves digestion, and releases tension in the back.\",\n      \"best_time_to_do\": \"Towards the end of your practice to promote relaxation and detoxification.\",\n      \"suggestions_tips\": \"Lengthen spine on each inhale, deepen twist on each exhale. Use a strap or hug knee to chest for deeper stretch.\"\n    },\n    {\n      \"name\": \"Corpse Pose\",\n      \"sanskrit_name\": \"Savasana\",\n      \"benefits\": \"Allows for complete relaxation and integration of yoga practice, reduces stress and promotes inner calm.\",\n      \"best_time_to_do\": \"At the end of your practice as a final relaxation pose.\",\n      \"suggestions_tips\": \"Lie down comfortably, close your eyes, and let go of any tension in your body. Focus on your breath and remain still.\"\n    }\n  ]\n}",
    "input: {\n  \"experience_level\": \"Intermediate\",\n  \"goals\": [\n    \"Flexibility\",\n    \"Relaxation\",\n    \"Strength\"\n  ],\n  \"limitations\": \"\"\n}",
    "output: {\n  \"yoga_poses\": [\n    {\n      \"name\": \"Triangle Pose\",\n      \"sanskrit_name\": \"Trikonasana\",\n      \"benefits\": \"Stretches the legs, hips, groin, spine, and shoulders; builds strength in the legs and ankles.\",\n      \"best_time_to_do\": \"As part of a standing sequence to improve balance and flexibility.\",\n      \"suggestions_tips\": \"Keep your back straight and your front knee aligned with your ankle. Gaze upwards or towards your front hand.\"\n    },\n    {\n      \"name\": \"Warrior II Pose\",\n      \"sanskrit_name\": \"Virabhadrasana II\",\n      \"benefits\": \"Strengthens legs, ankles, and core; improves balance and stretches the thighs, groin, and chest.\",\n      \"best_time_to_do\": \"As part of a standing sequence to improve strength and balance.\",\n      \"suggestions_tips\": \"Keep your front knee bent at a 90-degree angle and your back leg straight. Engage your core to maintain stability.\"\n    },\n    {\n      \"name\": \"Plank Pose\",\n      \"sanskrit_name\": \"Phalakasana\",\n      \"benefits\": \"Strengthens core, shoulders, and wrists; improves balance and prepares for other arm balances.\",\n      \"best_time_to_do\": \"As part of a flow sequence or as a transition between poses.\",\n      \"suggestions_tips\": \"Keep your body in a straight line from head to heels. Engage your core and keep your shoulders over your wrists.\"\n    },\n    {\n      \"name\": \"Boat Pose\",\n      \"sanskrit_name\": \"Paripurna Navasana\",\n      \"benefits\": \"Strengthens core, back, and legs; improves balance and coordination.\",\n      \"best_time_to_do\": \"Towards the end of your practice to challenge core strength and stability.\",\n      \"suggestions_tips\": \"Keep your back straight and your legs lifted off the ground. Engage your core to maintain balance.\"\n    },\n    {\n      \"name\": \"Supported Child's Pose\",\n      \"sanskrit_name\": \"Balasana with support\",\n      \"benefits\": \"Deeply relaxes the spine, hips, and shoulders; promotes relaxation and releases tension.\",\n      \"best_time_to_do\": \"As a resting pose or at the end of your practice for deep relaxation.\",\n      \"suggestions_tips\": \"Use a bolster or folded blankets to support your chest and forehead. Allow yourself to surrender into the pose and release tension.\"\n    }\n  ]\n}",
    f"input: {user_input}",
    "output: ",
  ])

  return response.text